
package ce.defs.domain

// Warning! This file is autogenerated.
// Source file ../../../../../../../cgen/dataclass.kts

data class DirsConfiguration(
    val workingDir: String = "",
    val tempDir: String = ""
) {
}
