package enums
// Warning! This file is autogenerated.
// Source file ../../../cgen/classes.kts

// File mode types
object ModeType {
    const val OREAD : Int = 0
    const val OWRITE : Int = 1
    const val ORDWR : Int = 2
    const val OEXEC : Int = 3
    const val OTRUNC : Int = 16
}
