package enums

import enums.CryptoCurrency

// Warning! This file is autogenerated.
// Source file ../../../cgen/classes.kts

data class Money(
    val sum: Int,
    val currency: CryptoCurrency,
    val name: String?,
    val attached: Boolean = false
)
