
package ce.defs

// Warning! This file is autogenerated.
// Source file ../../../../../../cgen/enums.kts

enum class Target(val rawValue: String) {
    Other("other"),
    Kotlin("kotlin"),
    C("c"),
    Cpp("cpp"),
    Swift("swift"),
    Java("java"),
    Rust("rust"),
    Go("go"),
    Python("python"),
    Meta("meta")
}
