package ce.defs// Warning! This file is autogenerated.
// Source file ../../../../../../cgen/enums.kts

data class TargetConfiguration(
    val outputFolder: String = "",
    val type: ce.defs.Target
) {
}
