#pragma once
// Warning! This file is autogenerated.
// Source file ../../cgen/classes.kts

namespace enums {

    // Enum CryptoCurrency
    enum CryptoCurrency {
        BTC,
        ETH,
        BCH
    }
}
