package ce.settings

import ce.defs.TargetConfiguration

data class Project(
    var files: List<String>,
    var codeStyle : CodeStyle,
    var targets: List<TargetConfiguration> = emptyList(),
    var addAutogeneratedCommentNotification : Boolean = false,
) {
    constructor() : this(emptyList(),
        CodeStyle(1, 4,),
        emptyList(),
        false)
}