package ce.settings

import ce.defs.TargetConfiguration
import ce.defs.domain.DirsConfiguration

data class Project(
    var files: List<String>,
    var codeStyle : CodeStyle,
    var targets: List<TargetConfiguration> = emptyList(),
    var addAutogeneratedCommentNotification : Boolean = false,
    var dirsConfiguration: DirsConfiguration = DirsConfiguration()
) {
    constructor() : this(emptyList(),
        CodeStyle(1, 4,),
        emptyList(),
        false)
}